version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    # volumes:
    #   - "./esdata:/usr/share/elasticsearch/data:z"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk_network  

  kibana:
    image: kibana:8.13.0
    environment:
      SERVER_NAME: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - elk_network  

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    # volumes:
    #   - "./logstash/config:/usr/share/logstash/config"
    ports:
      - "5044:5044"
    networks:
      - elk_network

networks:
  elk_network:
    name: elk_network
    