version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      # MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    networks:
      mysqldb-net:
  
    mysqlServer:
    image: mysql/mysql-server
    container_name: mysqldb-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tohir
      MYSQL_PASSWORD: 1234
    command: >
      bash -c "
      /entrypoint.sh mysqld &
      pid=\$!;
      sleep 10;
      mysql -uroot -proot -e \"
        CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
      \";
      wait \$pid
      "
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - mysqldb-net

volumes:
  mysqldata:

networks:
  mysqldb-net:
    name: mysqldb-net
    